version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_MCSP2406Project
  gitServerName: SIQA_Rima
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_SIQA_FeatureTests
  gitServerName: SIQA_Rima
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
