version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_MCSP2406Project
  gitServerName: SIQA_Rima
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_SIQA_FeatureTests
  version: "1.0"
  gitServerName: SIQA_Rima
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_mcsp2406.integrations:Call_getEmpDetails
  packages:
  - name: SIQA_GIT_MCSP2406Project
    version: "1.0"
  - name: TPP_SIQA_FeatureTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
- serviceName: tpp_siqa_featuretests.com.wm.featureTests.adapters:getEmpDetails
  packages:
  - name: TPP_SIQA_FeatureTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
